version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradlew bootRepackage
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build\libs\aws-training-note-0.0.1-SNAPSHOT.jar